name: repository-dispatch

on:
  repository_dispatch:
    types: ["trigger-event"]

env:
  ID: ${{ github.event.client_payload.id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: show context
        run: |
          echo "github sha is ${{ github.sha }}"
          echo "github.event is ${{ toJson(github.event) }}"
          echo "github.event_name is ${{ github.event_name }}"
      - name: run build
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "client_payload is ${{ github.event.client_payload }}"
  show-id:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: show id
        run: |
          echo "id is $ID"